homepage:
    path:     /
    defaults: { _controller: PIBundle:Default:accueil }


admin_homepage:
    path:     /accueil
    defaults: { _controller: PIBundle:Admin:index }


platform_admin_dashboard:
    path:     /dashboard
    defaults: { _controller: PIBundle:Admin:dashboard }

platform_admin_appartment:
    path:     /appartment
    defaults: { _controller: PIBundle:Admin:appartment }

form1:
    path:     /form1
    defaults: { _controller: PIBundle:Default:form1 }

ajouter:
    path:     /ajouter
    defaults: { _controller: PIBundle:Default:ajouter}

