homepage:
    path:     /
    defaults: { _controller: PIBundle:Default:accueil }


admin_homepage:
    path:     /accueil
    defaults: { _controller: PIBundle:Admin:index }


platform_admin_dashboard:
    path:     /dashboard
    defaults: { _controller: PIBundle:Admin:dashboard }