homepage:
    path:     /
    defaults: { _controller: PIBundle:Formulaire:accueil }

form1:
    path:     /user/formulaire_introduction
    defaults: { _controller: PIBundle:Formulaire:formulaire_introduction }

form2:
     path:     /user/formulaire_creerDemande
     defaults: { _controller: PIBundle:Formulaire:formulaire_creerDemande }
 
form2_modifier:
     path:     /user/formulaire_modifierDemande
     defaults: { _controller: PIBundle:Formulaire:formulaire_modifierDemande }

form3:
    path:     /user/formulaire_accederDemande
    defaults: { _controller: PIBundle:Formulaire:formulaire_accederDemande } 

contact:
    path:     /contact
    defaults: { _controller: PIBundle:Formulaire:contact }



redirection_acces:
    path:     /redirection_acces
    defaults: { _controller: PIBundle:Formulaire:redirection_access }

redirection_creer:
    path:     /redirection_creer
    defaults: { _controller: PIBundle:Formulaire:redirection_creer }  


platform_admin_dashboard:
    path:     /admin/dashboard
    defaults: { _controller: PIBundle:Admin:dashboard }

platform_admin_statistiques:
    path:     /admin/statistiques
    defaults: { _controller: PIBundle:Admin:statistiques }

platform_admin_appartment:
    path:     /admin/appartment
    defaults: { _controller: PIBundle:Admin:appartment }

platform_admin_ajouter_appartment:
    path:     /admin/ajouter_appartment
    defaults: { _controller: PIBundle:Admin:ajouter_appartment }

platform_admin_modifier_appartment:
    path:     /admin/modifier_appartment/{id}
    defaults: { _controller: PIBundle:Admin:modifier_appartment }

platform_admin_demandeur:
    path:     /admin/demandeur
    defaults: { _controller: PIBundle:Admin:demandeur }

platform_admin_ajouter_demandeur:
    path:     /admin/ajouter_demandeur
    defaults: { _controller: PIBundle:Admin:ajouter_demandeur }

platform_admin_modifier_demandeur:
    path:     /admin/modifier_demandeur/{id}
    defaults: { _controller: PIBundle:Admin:modifier_demandeur }

platform_admin_modifier_demande:
    path:     /admin/modifier_demande/{id}
    defaults: { _controller: PIBundle:Admin:modifier_demande }

platform_admin_ajouter_demande:
    path:     /admin/ajouter_demande/{id}
    defaults: { _controller: PIBundle:Admin:ajouter_demande }

platform_admin_etat_demande:
    path:     /admin/etat_demande/{id}
    defaults: { _controller: PIBundle:Admin:etat_demande }

platform_admin_affichage_demande:
    path:     /admin/affichage_demande/{id}
    defaults: { _controller: PIBundle:Admin:affichage_demande }

platform_admin_modifier_demande:
    path:     /admin/modifier_demande/{id}
    defaults: { _controller: PIBundle:Admin:modifier_demande }

platform_admin_valider_demande:
    path:     /admin/valider_demande
    defaults: { _controller: PIBundle:Admin:valider_demande }

platform_admin_confirmer_demande:
    path:     /admin/confirmer_demande/{id}
    defaults: { _controller: PIBundle:Admin:confirmer_demande }

platform_admin_refuser_demande:
    path:     /admin/refuser_demande/{id}
    defaults: { _controller: PIBundle:Admin:refuser_demande }

platform_admin_archiver_demande:
    path:     /admin/archiver_demande/{id}
    defaults: { _controller: PIBundle:Admin:archiver_demande }

platform_admin_attribution_demande:
    path:     /admin/attribution_demande/{id}
    defaults: { _controller: PIBundle:Admin:attribution_demande }

platform_admin_attribuer_demande:
    path:     /admin/attribuer_demande/{id}/{idappart}
    defaults: { _controller: PIBundle:Admin:attribuer_demande }

platform_admin_valider_attribution_demande:
    path:     /admin/valider_attribution_demande/{id}/{idappart}
    defaults: { _controller: PIBundle:Admin:valider_attribution_demande }

platform_admin_attribution_logement:
    path:     /admin/attribution_logement/{id}
    defaults: { _controller: PIBundle:Admin:attribution_logement }

platform_admin_attribuer_logement:
    path:     /admin/attribuer_logement/{id}/{iddemand}
    defaults: { _controller: PIBundle:Admin:attribuer_logement }

platform_admin_valider_attribution_logement:
    path:     /admin/valider_attribution_logement/{id}/{iddemand}
    defaults: { _controller: PIBundle:Admin:valider_attribution_logement }

platform_admin_archive:
    path:     /admin/archive
    defaults: { _controller: PIBundle:Admin:archive }

platform_admin_liberer_logement:
    path:     /admin/liberer_logment/{id}
    defaults: { _controller: PIBundle:Admin:liberer_logement }

platform_admin_affichage_archive:
    path:     /admin/affichage_archive/{id}
    defaults: { _controller: PIBundle:Admin:affichage_archive }

platform_admin_affichage_logement_archive:
    path:     /admin/affichage_logement_archive/{id}
    defaults: { _controller: PIBundle:Admin:affichage_logement_archive }

platform_admin_liberer_demande:
    path:     /admin/liberer_demande/{id}
    defaults: { _controller: PIBundle:Admin:liberer_demande }

platform_admin_afficher_locataire:
    path:     /admin/afficher_locataire/{id}
    defaults: { _controller: PIBundle:Admin:afficher_locataire }

platform_admin_delete_demand:
    path:     /admin/affichage_archive/{iduser}/{id}
    defaults: { _controller: PIBundle:Admin:delete_demand }

platform_admin_delete_appartment:
    path:     /admin/appartment/{id}
    defaults: { _controller: PIBundle:Admin:delete_appartment }

platform_admin_delete_user:
    path:     /admin/demandeur/{id}
    defaults: { _controller: PIBundle:Admin:delete_user }