homepage:
    path:     /
    defaults: { _controller: PIBundle:Default:accueil }


admin_homepage:
    path:     /accueil
    defaults: { _controller: PIBundle:Admin:index }

form1:
    path:     /form1
    defaults: { _controller: PIBundle:Default:form1 }

ajouter:
    path:     /ajouter
    defaults: { _controller: PIBundle:Default:ajouter}


platform_admin_dashboard:
    path:     /dashboard
    defaults: { _controller: PIBundle:Admin:dashboard }

platform_admin_appartment:
    path:     /appartment
    defaults: { _controller: PIBundle:Admin:appartment }

platform_admin_ajouter_appartment:
    path:     /ajouter_appartment
    defaults: { _controller: PIBundle:Admin:ajouter_appartment }

platform_admin_modifier_appartment:
    path:     /modifier_appartment/{id}
    defaults: { _controller: PIBundle:Admin:modifier_appartment }

platform_admin_demandeur:
    path:     /demandeur
    defaults: { _controller: PIBundle:Admin:demandeur }

platform_admin_ajouter_demandeur:
    path:     /ajouter_demandeur
    defaults: { _controller: PIBundle:Admin:ajouter_demandeur }

platform_admin_modifier_demandeur:
    path:     /modifier_demandeur/{id}
    defaults: { _controller: PIBundle:Admin:modifier_demandeur }

platform_admin_ajouter_demande:
    path:     /ajouter_demande/{id}
    defaults: { _controller: PIBundle:Admin:ajouter_demande }

platform_admin_etat_demande:
    path:     /etat_demande/{id}
    defaults: { _controller: PIBundle:Admin:etat_demande }

platform_admin_affichage_demande:
    path:     /affichage_demande/{id}
    defaults: { _controller: PIBundle:Admin:affichage_demande }

platform_admin_modifier_demande:
    path:     /modifier_demande/{id}
    defaults: { _controller: PIBundle:Admin:modifier_demande }

platform_admin_valider_demande:
    path:     /valider_demande
    defaults: { _controller: PIBundle:Admin:valider_demande }

platform_admin_confirmer_demande:
    path:     /confirmer_demande/{id}
    defaults: { _controller: PIBundle:Admin:confirmer_demande }

platform_admin_refuser_demande:
    path:     /refuser_demande/{id}
    defaults: { _controller: PIBundle:Admin:refuser_demande }

platform_admin_archiver_demande:
    path:     /archiver_demande/{id}
    defaults: { _controller: PIBundle:Admin:archiver_demande }

