<?php

namespace PIBundle\Repository;

/**
 * DemandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandRepository extends \Doctrine\ORM\EntityRepository
{
		public function findByMail($demand, $em){
	// 	$query = $em->createQuery('SELECT u FROM PIBundle\Entity\Demande u WHERE u.mail = '.$demande);

	// return $query->getResult();


	$query = $em->createQuery('
            SELECT u
            FROM PIBundle:Demand u
            WHERE u.email = :demand')
    ->setParameter('demand', $demand);

return $query->getResult();

	}
}
