<?php

namespace PIBundle\Repository;

/**
 * DemandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandRepository extends \Doctrine\ORM\EntityRepository
{
	public function findDemand($id){

	$query = $em->createQuery('SELECT u FROM PIBundle:Demand u WHERE u.idUser = $id and u.archived ="Non" ');
	return $query->getResult();
	}
}
