<?php

namespace PIBundle\Repository;

/**
 * DemandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandRepository extends \Doctrine\ORM\EntityRepository
{
}
