<?php

namespace PIBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findDemandeur($firstName, $lastName, $email)
	{
        $query = $this->createQueryBuilder('a');

        if($lastName != '')
        {
          $query->andWhere('a.lastName = :lastName')
                ->setParameter('lastName', $lastName);
        }

        if($email != '')
        {
          $query->andWhere('a.email = :email')
                ->setParameter('email', $email);
        }

        if($firstName != '')
        {
          $query->andWhere('a.firstName = :firstName')
                ->setParameter('firstName', $firstName);
        }


        return $query->getQuery()->getResult();

  }
}
